# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'PaypalBalance' do
    pod 'Toast-Swift'
    pod 'IQKeyboardManagerSwift'
end
target 'Widget' do
    #    pod 'Toast-Swift'
    pod 'Alamofire'
end
